# -*- coding: utf-8 -*-
"""Verifiable-ML-Model-Aggregator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15m0mx6iZnUb-O99uXuIyPdv6VkbQ4BHc
"""

# 1. Install Rust
!curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
import os
os.environ['PATH'] += ":/root/.cargo/bin"

# 2. Install Kani Verifier (This is what makes it "Verifiable")
!cargo install --locked kani-verifier
!cargo kani setup

# Write the Rust code to a file
with open("aggregator.rs", "w") as f:
    f.write("""
#[kani::proof]
fn verify_update_bounds() {
    // We simulate a model update (gradient) from a node
    let update: f32 = kani::any();

    // Logic: If the update is within safe bounds, we accept it
    let result = safe_aggregate(update);

    // Formal Verification: Prove that the result is NEVER outside -1 to 1
    assert!(result >= -1.0 && result <= 1.0);
}

fn safe_aggregate(val: f32) -> f32 {
    if val > 1.0 {
        return 1.0;
    } else if val < -1.0 {
        return -1.0;
    }
    val
}

fn main() {
    println!("Aggregator logic compiled.");
}
""")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile aggregator.rs
# #[kani::proof]
# fn verify_update_bounds() {
#     let update: f32 = kani::any();
# 
#     // We call our aggregation logic
#     let result = safe_aggregate(update);
# 
#     // Mathematically prove the result is always within safe bounds
#     assert!(result >= -1.0 && result <= 1.0);
# }
# 
# fn safe_aggregate(val: f32) -> f32 {
#     // Handle the NaN bug discovered in the previous run
#     if val.is_nan() {
#         return 0.0;
#     }
#     if val > 1.0 {
#         return 1.0;
#     } else if val < -1.0 {
#         return -1.0;
#     }
#     val
# }
# 
# fn main() {
#     println!("Aggregator logic ready for verification.");
# }

!kani aggregator.rs

# Save the success output to a file for your repo
with open("verification_report.txt", "w") as f:
    f.write("Kani Rust Verifier - Successful Formal Proof\n")
    f.write("Property: Bound Invariant (-1.0 <= x <= 1.0)\n")
    f.write("Status: VERIFIED\n")
    f.write("Vulnerability Mitigated: IEEE 754 NaN (Not-a-Number) Injection\n")

print("Verification report saved!")

import torch

# Simulated updates from 5 nodes
# Node 4 is a malicious actor trying to crash the system with a NaN
# Node 5 is an attacker sending a massive outlier (1000.0)
updates = torch.tensor([0.4, -0.1, 0.8, float('nan'), 1000.0])

def verified_aggregation_sim(tensors):
    # This Python logic mirrors your Verified Rust logic
    # 1. Neutralize NaNs
    clean_tensors = torch.nan_to_num(tensors, nan=0.0)
    # 2. Apply Verified Bounds (-1.0 to 1.0)
    bounded_tensors = torch.clamp(clean_tensors, min=-1.0, max=1.0)
    # 3. Aggregate
    return torch.mean(bounded_tensors)

final_update = verified_aggregation_sim(updates)
print(f"Aggregated Global Update: {final_update.item()}")
print("Result is secure, bounded, and NaN-free!")